import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["John", "Priya", "Arjun", "Neha"],
    "city": ["Mumbai", "Delhi", "Chennai", "Kolkata"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 3, 1, 5],
    "amount": [500, 650, 300, 800]
})

- perform an inner join on customer_id
- perform left join to show all customers and their order
- perform right join to show all orders and matching customers
- find customers who has no orders
- find orders that belong to customers not in the customers table

In [5]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["John", "Priya", "Arjun", "Neha"],
    "city": ["Mumbai", "Delhi", "Chennai", "Kolkata"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 3, 1, 5],
    "amount": [500, 650, 300, 800]
})

customers,orders

(   customer_id   name     city
 0            1   John   Mumbai
 1            2  Priya    Delhi
 2            3  Arjun  Chennai
 3            4   Neha  Kolkata,
    order_id  customer_id  amount
 0       101            1     500
 1       102            3     650
 2       103            1     300
 3       104            5     800)

In [7]:
inner_join=pd.merge(customers,orders,on='customer_id',how='inner')
inner_join

   customer_id   name     city  order_id  amount
0            1   John   Mumbai       101     500
1            1   John   Mumbai       103     300
2            3  Arjun  Chennai       102     650

In [11]:
left_join=pd.merge(customers,orders,on='customer_id',how='left')
left_join

   customer_id   name     city  order_id  amount
0            1   John   Mumbai     101.0   500.0
1            1   John   Mumbai     103.0   300.0
2            2  Priya    Delhi       NaN     NaN
3            3  Arjun  Chennai     102.0   650.0
4            4   Neha  Kolkata       NaN     NaN

In [13]:
right_join=pd.merge(customers,orders,on='customer_id',how='right')
right_join

   customer_id   name     city  order_id  amount
0            1   John   Mumbai       101     500
1            3  Arjun  Chennai       102     650
2            1   John   Mumbai       103     300
3            5    NaN      NaN       104     800

In [17]:
customers_no_order = customers[~customers['customer_id'].isin(orders['customer_id'])]
customers_no_order

   customer_id   name     city
1            2  Priya    Delhi
3            4   Neha  Kolkata

In [19]:
not_in_cust_table= orders[~orders['customer_id'].isin(customers['customer_id'])]
not_in_cust_table

   order_id  customer_id  amount
3       104            5     800