In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df1 = pd.read_csv(r"C:\Users\Rao\Documents\Naresh IT\DATA FILES\bank.csv")

In [27]:
df1

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

In [29]:
visa_df= pd.read_csv(r"C:\Users\Rao\Documents\Naresh IT\DATA FILES\Visadataset.csv")

In [31]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

- size
- shape
- len
- columns
- dtypes
- isnull
- head
- tail
- info

In [34]:
visa_df.shape

(25480, 12)

In [36]:
visa_df.size

305760

In [52]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [54]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [74]:
type(visa_df)

pandas.core.frame.DataFrame

In [76]:
type(visa_df.dtypes)

pandas.core.series.Series

In [72]:
visa_df.isnull().sum()

case_id                  0
continent                0
education_of_employee    0
has_job_experience       0
requires_job_training    0
no_of_employees          0
yr_of_estab              0
region_of_employment     0
prevailing_wage          0
unit_of_wage             0
full_time_position       0
case_status              0
dtype: int64

In [58]:
visa_df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [62]:
visa_df.tail()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [66]:
visa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   case_id                25480 non-null  object
 1   continent              25480 non-null  object
 2   education_of_employee  25480 non-null  object
 3   has_job_experience     25480 non-null  object
 4   requires_job_training  25480 non-null  object
 5   no_of_employees        25480 non-null  int64
 6   yr_of_estab            25480 non-null  int64
 7   region_of_employment   25480 non-null  object
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object
 10  full_time_position     25480 non-null  object
 11  case_status            25480 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

**task-1**
- i want to seperate the categorical and numerical columns

- cat columns in one list

- Numerical columns in another list

In [91]:
visa_df.dtypes.keys().tolist()

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'no_of_employees',
 'yr_of_estab',
 'region_of_employment',
 'prevailing_wage',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [83]:
visa_df.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [95]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [97]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [99]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [111]:
cols=visa_df.dtypes.keys().tolist()
cols

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'no_of_employees',
 'yr_of_estab',
 'region_of_employment',
 'prevailing_wage',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [107]:
dtype=visa_df.dtypes.values.tolist()
dtype

[dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('O')]

In [188]:
cat=[]
for i,j in zip(dtype,cols):
    if i=='object':
        cat.append(j)
cat

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [139]:
num=[]
for i,j in zip(dtype,cols):
    if i!='object':
        cat.append(j)
cat

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status',
 'no_of_employees',
 'yr_of_estab',
 'prevailing_wage']

In [141]:
cat=[j for i,j in zip(dtype,cols) if i=='object']
num=[j for i,j in zip(dtype,cols) if i!='object']
len(cat),len(num)

(9, 3)

**select dtype**

In [144]:
cat=visa_df.select_dtypes(include='object')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,region_of_employment,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,West,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,Northeast,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,West,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,West,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,South,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,South,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,Northeast,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,South,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,West,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,Midwest,Year,Y,Certified

In [148]:
num=visa_df.select_dtypes(exclude='object')
num

       no_of_employees  yr_of_estab  prevailing_wage
0                14513         2007         592.2029
1                 2412         2002       83425.6500
2                44444         2008      122996.8600
3                   98         1897       83434.0300
4                 1082         2005      149907.3900
...                ...          ...              ...
25475             2601         2008       77092.5700
25476             3274         2006      279174.7900
25477             1121         1910      146298.8500
25478             1918         1887       86154.7700
25479             3195         1960       70876.9100

[25480 rows x 3 columns]

**task-2 convert series to dataframe**

In [163]:
dtypes=visa_df.dtypes
d1=pd.DataFrame(dtypes,columns=['Data type'])
d1.reset_index().rename(columns={'index':'column'})

                   column Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [165]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [167]:
visa_df.dtypes.index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [169]:
dict(visa_df.dtypes)

{'case_id': dtype('O'),
 'continent': dtype('O'),
 'education_of_employee': dtype('O'),
 'has_job_experience': dtype('O'),
 'requires_job_training': dtype('O'),
 'no_of_employees': dtype('int64'),
 'yr_of_estab': dtype('int64'),
 'region_of_employment': dtype('O'),
 'prevailing_wage': dtype('float64'),
 'unit_of_wage': dtype('O'),
 'full_time_position': dtype('O'),
 'case_status': dtype('O')}

In [171]:
# if i have two list can i create
cols=visa_df.dtypes.index.tolist()
dtype=visa_df.dtypes.values.tolist()
pd.DataFrame(zip(cols,dtype))

                        0        1
0                 case_id   object
1               continent   object
2   education_of_employee   object
3      has_job_experience   object
4   requires_job_training   object
5         no_of_employees    int64
6             yr_of_estab    int64
7    region_of_employment   object
8         prevailing_wage  float64
9            unit_of_wage   object
10     full_time_position   object
11            case_status   object

**selection of data**

In [ ]:
visa_df.iloc[rows,columns]
visa_df.iloc[s:s:s,s:s:s]

In [176]:
visa_df
visa_df.iloc[100:105,3:6]  #100 to 104 3 to 5 cols

    has_job_experience requires_job_training  no_of_employees
100                  Y                     N             2227
101                  Y                     N              334
102                  Y                     N              224
103                  Y                     N              367
104                  Y                     N              306

In [178]:
visa_df.iloc[100:105] #100 to 104 rows from all cols

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
101,EZYV102,Asia,Master's,Y,N,334,2007,Midwest,43421.88,Year,Y,Certified
102,EZYV103,Asia,Bachelor's,Y,N,224,2008,Midwest,80253.78,Year,Y,Certified
103,EZYV104,Asia,Doctorate,Y,N,367,1982,West,115235.95,Year,Y,Certified
104,EZYV105,Asia,Master's,Y,N,306,2003,Northeast,95200.86,Year,N,Certified

In [180]:
visa_df.iloc[100] #100th row

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [182]:
visa_df.iloc[[100]]  #100th row df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified

In [184]:
visa_df.iloc[[100,200,300]]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [186]:
visa_df.iloc[[100,200,300],[1,5,9]]

    continent  no_of_employees unit_of_wage
100      Asia             2227         Year
200      Asia             3282         Year
300      Asia             3268         Year

In [ ]:
cols.index('')